spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/base-restful-api}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:pohodeui70}
    pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true